### ISSUE TITLE
workflow 16s error

### ISSUE THREAD

**Issue by BioinfoMonzino** [biobakery/biobakery_workflows#12]
Dear mantainers,
I'd like to use the biobakery workflow to perform my analysis on 16s data.
I'm currently using the Docker container ([https://hub.docker.com/r/biobakery/workflows](https://hub.docker.com/r/biobakery/workflows)).
However, after (1) downloading the gg references,
`wget ftp://greengenes.microbio.me/greengenes_release/gg_13_5/gg_13_8_otus.tar.gz
tar -xf gg_13_8_otus.tar.gz
` 
(2) properly setting the environment variables 
`export GREEN_GENES_DADA2_DB="./Ref_Biobakery_DB/green_genes_dada2_db"`

`export GREEN_GENES_FASTA_DB="./Ref_Biobakery_DB/green_genes_dada2_db/99_otus.fasta" # extracted by 'gg_13_8_otus/rep_set_aligned'`

`export GREEN_GENES_TAXONOMY_DB="./Ref_Biobakery_DB/green_genes_dada2_db/99_otu_taxonomy.txt" # extracted by 'gg_13_8_otus/taxonomy'`

and, (3) launching the workflow, I got stuck with this error:
`Traceback (most recent call last):
  File "/usr/local/bin/16s.py", line 182, in <module>
    workflow.go()
  File "/usr/local/lib/python3.6/dist-packages/anadama2/workflow.py", line 775, in go
    task_idxs = nx.algorithms.dag.topological_sort(self.dag, reverse=True)
TypeError: topological_sort() got an unexpected keyword argument 'reverse'
`
How could I solve this issue? I was expected that everything was perfect inside the container.

Thanks in advance,
Mattia

**Comment by ljmciver** [comment]
Hello, Sorry you are having issues and thank you for the detailed post! If you update to the latest docker container it should resolve the issue. Alternatively if you update your anadama2 install to the latest version that should solve the issue too.

Thank you,
Lauren
