### ISSUE TITLE
biobakery_workflows_databases not working

### ISSUE THREAD

**Issue by djbradshaw2** [biobakery/biobakery_workflows#2]
Dear Whom It May Concern, 

I am attempting to run the workflows tutorial (https://github.com/biobakery/biobakery/wiki/biobakery_workflows#121-install-with-conda) on Ubuntu 20.04 LTS on Windows Subsystem for Linux 2. The conda script was not working, so I moved on the the pip method and everything seemed to work installing-wise. But I get the following error when attempting to download the database with biobakery_workflows v0.15.1:

(base) root@DESKTOP-6BMVSG8:/mnt/c/Users/bradshawd# biobakery_workflows_databases --install wmgx_demo
Traceback (most recent call last):
  File "/usr/local/bin/biobakery_workflows_databases", line 5, in <module>
    from biobakery_workflows.biobakery_workflows_databases import main
  File "/usr/local/lib/python3.8/dist-packages/biobakery_workflows/biobakery_workflows_databases.py", line 30, in <module>
    from . import utilities
  File "/usr/local/lib/python3.8/dist-packages/biobakery_workflows/utilities.py", line 33, in <module>
    from anadama2.tracked import TrackedDirectory
  File "/usr/local/lib/python3.8/dist-packages/anadama2/__init__.py", line 83, in <module>
    from .workflow import Workflow
  File "/usr/local/lib/python3.8/dist-packages/anadama2/workflow.py", line 24, in <module>
    from . import backends
  File "/usr/local/lib/python3.8/dist-packages/anadama2/backends.py", line 7, in <module>
    import leveldb
SystemError: bad call flags

How do I solve this issue?

Thank you for your time and help. Please let me know if you need more information.

Sincerely, 

David

**Comment by djbradshaw2** [comment]
Dear Whom It May Concern,

The conda script is now working, I am unsure if I was doing something wrong or if someone updated it. So I am continuing with that install and will no longer need the pip install method. Thank you for whomever fixed that if it was not user error. Closing this issue down. Stay safe!

Sincerely, 

David
